---
title: 'Class #7.1'
author: "Hemanth Bharatha Chakravarthy"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(readr)
library(tidyverse)
library(fs)
library(janitor)
library(tidyr)
library(plotly)
library(lubridate)
library(zoo)
download.file(
  url = "https://pollofpolls.eu/get/polls/ES-parliament/format/csv",
  destfile = "spain.csv",
  mode = "wb"
  )

spain <- read_csv(
  "spain.csv",
   col_names = TRUE,
   cols(
    date = col_date(format = ""),
    firm = col_character(),
    n = col_double(),
    sd = col_double(),
    source = col_character(),
    Con = col_double(),
    Green = col_double(),
    Lab = col_double(),
    LibDem = col_double(),
    UKIP = col_double(),
    SNP = col_double()
    )) %>% 
  clean_names()

fs::file_delete("spain.csv")
```

# The interactive plot

```{r plotly}
# p <- plot_ly(uk, x = ~party, y = ~seats, type = 'scatter', mode = 'lines+markers')x
list <- spain %>% 
  group_by(firm) %>% 
  summarise(n = n()) %>% 
  filter(n >= 40) %>% 
  ungroup(firm)

plot <- spain %>% 
  group_by(firm) %>% 
  inner_join(list, by = "firm") %>% 
  filter(date > "2018-03-01") %>%
  gather(party, count, pp:p_de_cat) %>% 
  group_by(date, party) %>% 
  summarise(mean_f = mean(count)) %>% 
  spread(key = party, value = mean_f) %>% 
  ungroup()

plot$date <- format(plot$date, "%d/%B/%Y")

p <- plot_ly(plot, x = ~date, y = ~pp, name = 'PP', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~psoe, name = 'PSOE', mode = 'lines+markers') %>% 
  add_trace(y = ~bng, name = 'BNG', mode = 'lines+markers') %>%
  add_trace(y = ~cc, name = 'CC', mode = 'lines+markers') %>% 
  add_trace(y = ~erc, name = 'ERC', mode = 'lines+markers') %>%
  add_trace(y = ~cs, name = 'CS', mode = 'lines+markers') %>% 
  add_trace(y = ~vox, name = 'VOX', mode = 'lines+markers') %>% 
  add_trace(y = ~podemos, name = 'PODEMOS', mode = 'lines+markers') %>% 
  add_trace(y = ~eh_bildu, name = 'EH Bildu', mode = 'lines+markers') %>% 
  add_trace(y = ~p_de_cat, name = 'PDeCat', mode = 'lines+markers') %>% 
  layout(title = "1 Year Election Polls", 
          yaxis = list(title = "Seats"), 
          xaxis = list(title = "Date"))

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
Sys.setenv("plotly_username"="wtannergildea")
Sys.setenv("plotly_api_key"="qgHNIc7BXBaZ7wIRIdoS")

chart_link = api_create(p, filename="line-basic")
chart_link

```

https://plot.ly/~wtannergildea/1/#/